"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const source = fs.readFileSync(path.join(__dirname, "PostgresStateAdapter.js"), "utf8");
assert(source.includes("BEGIN"), "durable write must open a transaction");
assert(source.includes("pg_advisory_xact_lock"), "cross-instance writers must be serialized");
assert(source.includes("FOR UPDATE"), "state row must be locked during update");
assert(source.includes("COMMIT"), "success must be acknowledged only after COMMIT");
assert(source.includes("ROLLBACK"), "failed writes must rollback");
assert(source.includes("revision=app_state.revision+1"), "state revision must advance atomically");
console.log("PostgreSQL transaction integrity policy tests passed");
