github.com:
    users:
        muhamed1986ddg-dotcom:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: muhamed1986ddg-dotcom
