"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const server=fs.readFileSync(path.join(__dirname,"..","server.js"),"utf8");
const store=fs.readFileSync(path.join(__dirname,"..","store.js"),"utf8");
const access=fs.readFileSync(path.join(__dirname,"..","access-control.js"),"utf8");
assert(server.includes('app.get("/api/monthly-inventory"'),"monthly inventory GET route missing");
assert(server.includes('app.post("/api/monthly-inventory/close"'),"monthly inventory close route missing");
assert(server.includes('app.patch("/api/monthly-inventory/settings"'),"monthly inventory settings route missing");
assert(server.includes('store.monthlyInventories.push(item)'),"inventory snapshot is not persisted");
assert(store.includes('monthlyInventories'),"monthly inventories are not normalized in store");
assert(access.includes('/api/monthly-inventory/close'),"inventory route permissions missing");
assert(server.includes('function calculateInventoryNetCapital(store)'),"inventory must source net capital from the budget equation");
assert(server.includes('netCapital:round(capital.netCapital)'),"inventory snapshot must store net capital");
assert(server.includes('finalValue:round(capital.netCapital+normalizedVault)'),"inventory formula must be net capital + manual vault cash");
const netCapital=262445.16,vaultCash=19909.83;
assert.strictEqual(+(netCapital+vaultCash).toFixed(2),282354.99);
for(const day of [1,20,28])assert(day>=1&&day<=28);
console.log("MonthlyInventory.test.js: OK");
