"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const server=fs.readFileSync(path.join(__dirname,"..","server.js"),"utf8");
const store=fs.readFileSync(path.join(__dirname,"..","store.js"),"utf8");
const access=fs.readFileSync(path.join(__dirname,"..","access-control.js"),"utf8");
const financials=fs.readFileSync(path.join(__dirname,"MonthlyInventoryFinancials.js"),"utf8");
const reports=fs.readFileSync(path.join(__dirname,"..","..","..","frontend","src","screens","ReportsProfits.jsx"),"utf8");
assert(server.includes('app.get("/api/monthly-inventory"'),"monthly inventory GET route missing");
assert(server.includes('app.post("/api/monthly-inventory/close"'),"monthly inventory close route missing");
assert(server.includes('app.post("/api/monthly-inventory/preview"'),"official inventory preview route missing");
assert(server.includes('app.patch("/api/monthly-inventory/settings"'),"monthly inventory settings route missing");
assert(server.includes('store.monthlyInventories.push(item)'),"inventory snapshot is not persisted");
assert(store.includes('monthlyInventories'),"monthly inventories are not normalized in store");
assert(access.includes('/api/monthly-inventory/close'),"inventory route permissions missing");
assert(access.includes('/api/monthly-inventory/preview'),"inventory preview route permissions missing");
assert(server.includes('function calculateInventoryNetCapital(store)'),"inventory must calculate equity independently");
assert(server.includes('calculateInventoryPosition(store'),"inventory must collect canonical asset and liability components");
assert(server.includes('const snapshot=calculateInventorySnapshot({'),"inventory must use the approved net-assets equation");
assert(server.includes('calculateVaultCashSnapshot(req.body.vaultCashByCurrency'),"multi-currency vault cash must be converted on the server");
assert(server.includes('legacyVaultCashDetails(stableItem.vaultCash)'),"legacy scalar vault cash must remain compatible");
assert(server.includes('...(vaultCashExchangeRates?{vaultCashExchangeRates}:{})'),"inventory snapshot must persist the exchange-rate snapshot");
assert(financials.includes('inventoryDifference:moneyToNumber(inventoryDifference)'),"inventory snapshot must expose the reconciliation difference");
assert(reports.includes('inventoryDisplay.finalInventory??inventoryDisplay.finalValue'),"inventory UI must display the official backend final inventory");
assert(!reports.includes('const previewFinalValue=previewTotalAssets-previewTotalLiabilities'),"inventory UI must not recalculate final inventory");
for(const day of [1,20,28])assert(day>=1&&day<=28);
console.log("MonthlyInventory.test.js: OK");
