BEGIN;
CREATE UNIQUE INDEX IF NOT EXISTS users_company_email_uq ON users(company_id, lower(email)) WHERE email IS NOT NULL;
CREATE INDEX IF NOT EXISTS customers_company_name_idx ON customers(company_id, lower(name));
CREATE INDEX IF NOT EXISTS customers_company_phone_idx ON customers(company_id, phone);
CREATE INDEX IF NOT EXISTS transactions_company_date_idx ON transactions(company_id, transaction_date DESC);
CREATE INDEX IF NOT EXISTS transactions_customer_idx ON transactions(customer_id);
CREATE INDEX IF NOT EXISTS transactions_partner_idx ON transactions(partner_id);
CREATE INDEX IF NOT EXISTS transactions_status_idx ON transactions(company_id, status);
CREATE INDEX IF NOT EXISTS transactions_currency_idx ON transactions(company_id, currency);
CREATE INDEX IF NOT EXISTS payments_company_date_idx ON payments(company_id, payment_date DESC);
CREATE INDEX IF NOT EXISTS debts_company_direction_status_idx ON debts(company_id, direction, status);
CREATE INDEX IF NOT EXISTS debts_customer_idx ON debts(customer_id);
CREATE INDEX IF NOT EXISTS debts_due_date_idx ON debts(company_id, due_date) WHERE status <> 'paid';
CREATE INDEX IF NOT EXISTS expenses_company_date_idx ON expenses(company_id, expense_date DESC);
CREATE INDEX IF NOT EXISTS expenses_category_idx ON expenses(company_id, category);
CREATE INDEX IF NOT EXISTS capital_company_date_idx ON capital_movements(company_id, movement_date DESC);
CREATE INDEX IF NOT EXISTS exchange_rates_pair_date_idx ON exchange_rates(company_id, base_currency, quote_currency, effective_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_company_date_idx ON audit_logs(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_entity_idx ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS system_events_type_date_idx ON system_events(event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS system_events_severity_date_idx ON system_events(severity, created_at DESC);
COMMIT;
