const fs=require('fs');
const assert=require('assert');
const server=fs.readFileSync(__dirname+'/server.js','utf8');
assert(server.includes('app.delete("/api/transactions/:id", auth, async (req,res)=>{'));
assert(server.includes('persisted?.isDeleted'));
assert(server.includes('تم حذف الحوالة بنجاح'));
const tx=fs.readFileSync(__dirname+'/../../frontend/src/screens/Transactions.jsx','utf8');
assert(tx.includes('async function deleteTransaction(transaction)'));
assert(tx.includes('api.delete(`/transactions/${transaction.id}`)'));
assert(tx.includes('title="حذف"'));
const customer=fs.readFileSync(__dirname+'/../../frontend/src/screens/CustomerDetails.jsx','utf8');
assert(customer.includes('api.delete(`/transactions/${transactionId}`)'));
assert(customer.includes('clearApiGetCache();'));
console.log('Delete transaction integration test passed');
