const fs=require('fs');
const assert=require('assert');
const api=fs.readFileSync(__dirname+'/../../frontend/src/api.js','utf8');
const server=fs.readFileSync(__dirname+'/server.js','utf8');
assert(api.includes('_alaboudWriteReplayCount'));
assert(api.includes('"Idempotency-Key":operationKey'));
assert(api.includes('const replay=await axios.request(replayConfig)'));
assert(api.includes('DUPLICATE_OPERATION_IN_PROGRESS')||api.includes('409 means the first request'));
assert(server.includes('committed:true'));
assert(!server.includes('const persisted=readStore().transactions.find(item=>item.id===deleted.id)'));
console.log('Edit/delete reliability v25.14.16 test passed');
