const fs=require("fs"),path=require("path"),assert=require("assert");
const server=fs.readFileSync(path.join(__dirname,"server.js"),"utf8");
const adapter=fs.readFileSync(path.join(__dirname,"database/adapters/PostgresStateAdapter.js"),"utf8");
assert(server.includes('process.env.NATIVE_INTERACTIVE_READS || "false"'),"interactive memory-read switch missing");
assert(server.includes('!nativeInteractiveReadsEnabled'),"interactive fallback is not preferred");
assert(adapter.includes('process.env.PG_POOL_MIN || 1'),"warm pool minimum missing");
assert(adapter.includes('process.env.PG_IDLE_TIMEOUT_MS || 900000'),"warm pool idle timeout missing");
assert(adapter.includes('process.env.RELATIONAL_MIRROR_DELAY_MS || 1500'),"mirror coalescing delay missing");
assert(adapter.includes('this.mirrorScheduleTimer'),"mirror scheduling guard missing");
assert(adapter.includes('await client.query("COMMIT")'),"durable commit confirmation was removed");
console.log("Fast interactive operations v25.14.14 test passed");
