const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'../..');
const server=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const store=fs.readFileSync(path.join(root,'backend/src/store.js'),'utf8');
assert(server.includes('apiKeyMiddleware({readStore,telemetry:telemetryWriter,now,id})'),'API-key activity telemetry must use the isolated telemetry writer');
assert(server.includes('integrationLogger({telemetry:telemetryWriter,now,id})'),'integration request logs must use the isolated telemetry writer');
const block=(store.match(/function mutateVolatile\(fn\)\{[\s\S]*?\n\}/)||[])[0]||'';
assert(block,'mutateVolatile helper must exist');
assert(!block.includes('writeStore('),'mutateVolatile must not invoke writeStore/queueSave');
assert(block.includes('database.replaceStore(rootStore)'),'mutateVolatile should keep DatabaseService in-memory view aligned');
assert(store.includes('mutate,mutateVolatile,mutateDurable'),'mutateVolatile must be exported');
console.log('v25.14.60 JAD revision-isolation guard: OK');
