const fs=require("fs");const path=require("path");const assert=require("assert");
const root=path.resolve(__dirname,"../..");
const server=fs.readFileSync(path.join(root,"backend/src/server.js"),"utf8");
const api=fs.readFileSync(path.join(root,"frontend/src/api.js"),"utf8");
const login=fs.readFileSync(path.join(root,"frontend/src/LoginShell.jsx"),"utf8");
const shell=fs.readFileSync(path.join(root,"frontend/src/AppShell.jsx"),"utf8");
const android=fs.readFileSync(path.join(root,"app/src/main/java/com/alaboud/businesssuite/MainActivity.kt"),"utf8");
assert(server.includes('httpOnly:true'));
assert(server.includes('sameSite:"lax"'));
assert(server.includes('secure:IS_PROD'));
assert(server.includes('const token=bearerToken||cookieToken'));
assert(server.includes('CSRF_ORIGIN_REJECTED'));
assert(server.includes('clearSessionCookie(res)'));
assert(server.includes('clientSupportsCookieOnlySession'));
assert(server.includes('sessionResponseBody(req,session)'));
assert(api.includes('withCredentials:true'));
assert(login.includes('localStorage.removeItem("afs_token")'));
assert(!login.includes('localStorage.setItem("afs_token",data.token)'));
assert(shell.includes('api.get("/auth/session"'));
assert(shell.includes('localStorage.removeItem("afs_token")'));
assert(!android.includes("localStorage.getItem('afs_token')"));
console.log("v25.14.50 secure HttpOnly session wiring: OK");
