"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const server=fs.readFileSync(path.join(__dirname,"server.js"),"utf8");
const idem=fs.readFileSync(path.join(__dirname,"reliability","idempotency.js"),"utf8");
const adapter=fs.readFileSync(path.join(__dirname,"database","adapters","PostgresStateAdapter.js"),"utf8");
assert(idem.includes("scope_key=$1 AND operation_key=$2"),"durable idempotency lookup must be tenant scoped");
assert(adapter.includes("uq_operation_receipts_scope_key"),"operation receipts need tenant-scoped unique index");
assert(adapter.includes("ON CONFLICT (scope_key,operation_key,method,path)"),"receipt upsert must use tenant scope");
assert(server.includes("getScope: idempotencyTenantScope"),"idempotency middleware must resolve tenant scope");
assert(server.includes("async function assertSafePartnerUrl"),"partner SSRF guard missing");
assert(server.includes("await assertSafePartnerUrl(currentUrl)"),"connector fetch must validate every outbound URL");
assert(server.includes("await assertSafePartnerUrl(nextUrl)"),"connector redirects must be revalidated");
assert(server.includes("ignoreHTTPSErrors:false"),"browser connector must not bypass TLS validation");
assert(server.includes('request.resourceType()!=="document"'),"browser navigation SSRF guard missing");
assert(server.includes("revokeUserSessions(store,user.id,user.id,req.user.jti)"),"password change must revoke other sessions");
assert(server.includes("revokeUserSessions(root,user.id,user.id,null)"),"password reset must revoke all sessions");
assert(server.includes("revokeBiometricForUser"),"password changes must revoke biometric tokens");
console.log("v25.14.55 security + tenant isolation hardening: OK");
