"use strict";
const assert=require("assert");
const fs=require("fs");const path=require("path");
const server=fs.readFileSync(path.join(__dirname,"server.js"),"utf8");
const store=fs.readFileSync(path.join(__dirname,"store.js"),"utf8");
const api=fs.readFileSync(path.join(__dirname,"api-platform.js"),"utf8");
const migration=fs.readFileSync(path.join(__dirname,"../migrations/20260811_telemetry_isolation_v251461.sql"),"utf8");
assert(server.includes("createTelemetryWriter"));
assert(server.includes("apiKeyMiddleware({readStore,telemetry:telemetryWriter,now,id})"));
assert(server.includes("integrationLogger({telemetry:telemetryWriter,now,id})"));
assert(!api.includes("integrationLogger({mutate"));
assert(!api.includes("apiKeyMiddleware({readStore,mutate"));
assert(migration.includes("CREATE TABLE IF NOT EXISTS integration_logs"));
assert(migration.includes("CREATE TABLE IF NOT EXISTS api_key_activity"));
assert(migration.includes("integration_logs_company_created_idx"));
assert(migration.includes("api_key_activity_company_created_idx"));
assert(!migration.match(/\bUPDATE\b|\bUPSERT\b/i));
const durable=(store.match(/function mutateDurable\(fn\)\{[\s\S]*?\n\}/)||[])[0]||"";
assert(durable.includes("structuredClone(rootStore)"));
assert(durable.includes("database.saveDurable"));
console.log("v25.14.61 telemetry isolation regression: OK");
