const assert=require('assert');
const pkg=require('../package.json');
const fpkg=require('../../frontend/package.json');
const bpkg=require('./../package.json');
assert.strictEqual(pkg.version,'25.14.37');
assert.strictEqual(fpkg.version,'25.14.37');
assert.strictEqual(bpkg.version,'25.14.37');
const {APP_VERSION}=require('./production-readiness');
assert.strictEqual(APP_VERSION,'25.14.37');
console.log('version consistency v25.14.37: OK');
