"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const adapter = fs.readFileSync(path.join(__dirname,"adapters","PostgresStateAdapter.js"),"utf8");
const server = fs.readFileSync(path.join(__dirname,"..","server.js"),"utf8");
assert.match(adapter,/attemptError\s*=\s*error/,'failed checked-out clients must be destroyed on release');
assert.match(adapter,/client\.release\(Boolean\(attemptError\)\)/,'release must destroy failed clients');
assert.match(adapter,/ambiguous-commit:/,'ambiguous COMMIT must be verified on a fresh pool');
assert.match(adapter,/SELECT app_revision FROM operation_receipts WHERE operation_key=\$1 AND status='COMMITTED'/,'receipt verification must be durable');
assert.match(adapter,/Do not reset the entire pool from the checked-out client's error/,'checked-out client errors must not reset the whole pool asynchronously');
assert.match(server,/تعذر تأكيد التعديل الآن بسبب اتصال قاعدة البيانات/,'transaction edit must expose retryable 503');
assert.match(server,/تعذر تأكيد الحذف الآن بسبب اتصال قاعدة البيانات/,'transaction delete must expose retryable 503');
console.log('PostgreSQL broken-client edit/delete recovery v25.14.17 test passed');
