import React,{useEffect,useRef,useState}from"react";
import api,{cachedGet} from"../api";
import {APP_VERSION} from"../version";
import {money,cad,openRegularWhatsApp,currencyFlag,flagOf,cleanConnectorMessage,EXCHANGE_CURRENCY_CATALOG,debtCurrencies,CurrencyFlag,rateTrend} from"../shared";

function AICommandCenter({navigate}){
  const [overview,setOverview]=useState(null);const [question,setQuestion]=useState("");const [messages,setMessages]=useState([{role:"assistant",text:"مرحبًا، أنا مساعد العبود الذكي. اسألني عن الأرباح أو المصروفات أو الديون أو التوقعات."}]);const [busy,setBusy]=useState(false);const [listening,setListening]=useState(false);
  const load=()=>cachedGet("/ai/overview").then(r=>setOverview(r.data)).catch(()=>{});
  useEffect(()=>{load()},[]);
  async function ask(text=question){const q=String(text||"").trim();if(!q||busy)return;setQuestion("");setMessages(m=>[...m,{role:"user",text:q}]);setBusy(true);try{const {data}=await api.post("/ai/assistant",{question:q});setMessages(m=>[...m,{role:"assistant",text:data.answer,data:data.data||[],action:data.action}]);setOverview(data.overview||overview)}catch(e){setMessages(m=>[...m,{role:"assistant",text:e.response?.data?.message||"تعذر تنفيذ التحليل الآن."}])}finally{setBusy(false)}}
  function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("الإدخال الصوتي غير مدعوم في هذا المتصفح");return}const r=new SR();r.lang="ar-SA";r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=e=>{const t=e.results[0][0].transcript;setQuestion(t);ask(t)};r.start()}
  if(!overview)return <div className="premium-loading">جاري تشغيل مركز الذكاء…</div>;
  return <section className="ai-center">
    <div className="ai-hero"><div><span>🤖</span><div><h2>مركز القيادة الذكي</h2><p>ALABOUD AI — تحليل الأعمال واتخاذ القرار</p></div></div><b className={overview.healthScore>=75?"good":overview.healthScore>=50?"warn":"bad"}>صحة الشركة {overview.healthScore}/100</b></div>
    <div className="ai-kpis"><article className={Number(overview.today.netProfit||0)<0?"value-negative":"value-positive"}><span>صافي اليوم</span><strong>{cad(overview.today.netProfit)}</strong></article><article className={Number(overview.month.netProfit||0)<0?"value-negative":"value-positive"}><span>صافي الشهر</span><strong>{cad(overview.month.netProfit)}</strong></article><article className="value-receivable"><span>الديون لنا</span><strong>{cad(overview.finance.receivables)}</strong></article><article className={Number(overview.forecast.nextMonthNet||0)<0?"value-negative":"value-positive"}><span>توقع الشهر القادم</span><strong>{cad(overview.forecast.nextMonthNet)}</strong></article></div>
    <div className="ai-intelligence-grid">
      <article className="card ai-trend-card"><div className="section-heading"><h3>📊 اتجاه الأداء خلال 6 أشهر</h3><small>الأرباح والمصروفات وصافي النتيجة</small></div><div className="ai-trend-bars">{overview.monthlyTrend.map((item)=>{const max=Math.max(1,...overview.monthlyTrend.flatMap(x=>[Math.abs(x.profit||0),Math.abs(x.expenses||0),Math.abs(x.net||0)]));return <div className="ai-trend-column" key={item.month}><div className="ai-trend-stack"><i className="profit" style={{height:`${Math.max(6,Math.abs(item.profit||0)/max*100)}%`}} title={`الأرباح ${cad(item.profit)}`}></i><i className="expense" style={{height:`${Math.max(6,Math.abs(item.expenses||0)/max*100)}%`}} title={`المصروفات ${cad(item.expenses)}`}></i><i className={item.net>=0?"net positive":"net negative"} style={{height:`${Math.max(6,Math.abs(item.net||0)/max*100)}%`}} title={`الصافي ${cad(item.net)}`}></i></div><span>{item.month.slice(5)}</span></div>})}</div><div className="ai-chart-legend"><span>● الأرباح</span><span>● المصروفات</span><span>● الصافي</span></div></article>
      <article className="card ai-decision-card"><div className="section-heading"><h3>🎯 مركز القرارات</h3><small>إجراءات مقترحة الآن</small></div>{overview.recommendations.slice(0,4).map((x,i)=><button key={i} onClick={()=>{if(/دين|تحصيل/.test(x))navigate("customers");else if(/مصروف/.test(x))navigate("expenses");else if(/سيولة|رأس/.test(x))navigate("capital-overview");else navigate("monthly-report")}}><span>{i+1}</span><p>{x}</p><b>تنفيذ ›</b></button>)}</article>
    </div>
    <div className="ai-layout"><div className="ai-chat card"><div className="ai-messages">{messages.map((m,i)=><div key={i} className={`ai-message ${m.role}`}><p>{m.text}</p>{m.data?.length>0&&<div className="ai-results">{m.data.slice(0,6).map((x,j)=><div key={x.id||j}><strong>{x.name||x.title||x.number||"سجل"}</strong><span>{x.finalBalance!==undefined?cad(x.finalBalance):x.amount!==undefined?`${x.amount} ${x.currency||""}`:""}</span></div>)}</div>}{m.action&&<button onClick={()=>navigate(m.action.page)}>فتح الصفحة</button>}</div>)}{busy&&<div className="ai-message assistant"><p>جاري التحليل…</p></div>}</div><form onSubmit={e=>{e.preventDefault();ask()}} className="ai-input"><button type="button" onClick={voice}>{listening?"◉":"🎙️"}</button><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="اسأل: كم أرباح هذا الشهر؟"/><button>إرسال</button></form><div className="ai-quick">{["كم أرباح اليوم؟","اعرض الديون المتأخرة","حلل المصروفات","ما توقع الشهر القادم؟","قيّم صحة الشركة"].map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div></div>
    <aside className="ai-side"><div className="card"><h3>💡 توصيات اليوم</h3>{overview.recommendations.map((x,i)=><p key={i}>• {x}</p>)}</div><div className="card"><h3>🚨 اكتشاف تلقائي</h3>{overview.anomalies.length?overview.anomalies.map((x,i)=><div key={i} className={`ai-alert ${x.level}`}><strong>{x.title}</strong><small>{x.message}</small></div>):<p>لا توجد أخطاء غير اعتيادية.</p>}</div><div className="card"><h3>🖥️ مراقبة النظام</h3><p>قاعدة البيانات: <b>{overview.system.database}</b></p><p>المستخدمون: <b>{overview.system.users}</b></p><p>الأجهزة النشطة: <b>{overview.system.devices}</b></p><button onClick={()=>navigate("settings")}>النسخ الاحتياطي والإعدادات</button></div></aside></div>
  </section>
}

export { AICommandCenter };
